services:
    OHMedia\SettingsBundle\Settings\Settings:
        arguments: ["@doctrine.orm.entity_manager"]
    
    ohmedia_settings.settings:
        alias: OHMedia\SettingsBundle\Settings\Settings

    ohmedia_settings.twig_extension:
        class: OHMedia\SettingsBundle\Twig\SettingsExtension
        arguments: ["@ohmedia_settings.settings"]
        tags:
            - { name: twig.extension }
