services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\SettingsBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaSettingsBundle.php'

    # alias used in SettingsPass
    oh_media_settings.settings: '@OHMedia\SettingsBundle\Service\Settings'
